---
name: CGI-Application-Util-Diff
version: 1.00
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: 'Diff 2 directories or files, or run other commands'
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Algorithm::Diff: 0
  CGI: 0
  CGI::Application: 0
  CGI::Application::Dispatch: 0
  Carp: 0
  Config::Tiny: 0
  DBD::CSV: 0
  DBI: 0
  FCGI::ProcManager: 0
  File::stat: 0
  HTML::Entities::Interpolate: 0
  HTML::Template: 0
  Hash::FieldHash: 0
  IPC::Capture: 0
  JSON::XS: 0
  Path::Class: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Application::Util::Diff:
    file: lib/CGI/Application/Util/Diff.pm
    version: 1.00
  CGI::Application::Util::Diff::Actions:
    file: lib/CGI/Application/Util/Diff/Actions.pm
    version: 1.00
  CGI::Application::Util::Diff::Config:
    file: lib/CGI/Application/Util/Diff/Config.pm
    version: 1.00
  CGI::Application::Util::Logger:
    file: lib/CGI/Application/Util/Logger.pm
    version: 1.00
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
