#!/bin/bash

cd /home/ron/perl.modules/CGI-Application-Util-Diff

cp -r /home/ron/httpd/prefork/htdocs/assets/css/cgi/application/util       htdocs/assets/css/cgi/application/
cp -r /home/ron/httpd/prefork/htdocs/assets/templates/cgi/application/util htdocs/assets/templates/cgi/application/
cp    /home/ron/httpd/prefork/htdocs/local/util.diff                       htdocs/local
cp    /home/ron/httpd/prefork/cgi-bin/util.diff.cgi                        httpd/cgi-bin
